import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:8000`)
  console.log('Res: ', JSON.stringify(res))
  //const data = await res.json()
  const data = JSON.stringify(res)
  //const data = await res.json()

  return { props: { data } }
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <p>Hello World</p>
        {process.env.backendUrl}
        <h3>{data}</h3>
      </main>
    </>
  )
}
